site_name: Flow-IQ Docs
nav:
  - Home: index.md
  - Getting Started: 
    - getting-started/about-flowiq.md
    - getting-started/what-you-should-know.md
  - User Guide:
    - user-guide/index.md
    - user-guide/step1-locate-module.md
    - user-guide/step2-understanding-nfcore-modules.md
    - user-guide/step3-create-pipeline.md
    - user-guide/step4-install-manta-module.md
    - user-guide/step5-build-a-one-step-workflow.md
    - user-guide/step6-test-on-biowulf.md
    - user-guide/step7-prepare-for-aws-healthomics.md
    - user-guide/step8-deploy-to-aws-healthomics.md
  - Troubleshooting & Tips: 
    - user-guide/troubleshooting-and-tips.md
  - Explorer: 
    - explorer/index.md

extra_css:
  - https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css
  - explorer/stylesheets/extra.css

extra_javascript:
  - https://code.jquery.com/jquery-3.6.0.min.js
  - https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js

theme: readthedocs

#extra:
#  social:
#    - icon: fontawesome/brands/github
#      link: https://github.com/NCI-DCEG/Flow-IQ
